### ISSUE TITLE
Footer Not Changes

### ISSUE THREAD

**Issue by abunayeem11111** [vietrick/Blogger#1]
Sir, no matter how much I tried to change the footer, I could not. It would be better if you remove your custom footer. thank you

**Comment by abunayeem11111** [comment]
![Screenshot_20220821-030337](https://user-images.githubusercontent.com/111665216/185768709-02a27a79-fd38-4d7b-8ba3-aa4141f4519d.jpg)

**Comment by BazilaAfridi** [comment]
Did anyone solve this issue?
please help us how to remove the footer text "designed by vietrick"

**Comment by vietrick** [comment]
Hi,
The latest VTrick template has removed the footer credit.

Regards,
